import '@/styles/globals.scss'

import clsx from 'clsx'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { notFound } from 'next/navigation'
import { NextIntlClientProvider, useMessages } from 'next-intl'

import Navbar from '@/components/partials/navbar/Navbar'
import Sidebar from '@/components/partials/sidebar/Sidebar'
import { AppConfig } from '@/config/app'
import { ThemeRegistry } from '@/config/theme'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NextJS - Boilerplate',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  // Validate that the incoming `locale` parameter is valid
  if (!AppConfig.locales.includes(locale)) notFound()

  // Using internationalization in Client Components
  const messages = useMessages()

  return (
    <html lang={locale}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.css"
        />
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js"
          async
        />
      </head>
      <body className={inter.className} id="app">
        <ThemeRegistry>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Navbar />

            <Sidebar />

            <div className="mt-14 p-4 sm:ml-64">{children}</div>
          </NextIntlClientProvider>
        </ThemeRegistry>
      </body>
    </html>
  )
}
